name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Format
        run: deno bundle index.tsx index.bundle.tsx

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "bright-fly-34"
          entrypoint: "./index.bundle.tsx"
